### ISSUE TITLE
Aquarium with Luminati Proxy not working

### ISSUE THREAD

**Issue by Urahara** [TeamHG-Memex/aquarium#22]
I'm trying to configure Aquarium to work with Luminati Proxy, but everytime i try to make a request using the proxy, example: "127.0.0.1:24000" i get this exception:

> loadFinished: RenderErrorInfo(type='Network', code=99, text='Proxy connection refused', url='https://www.example.com/')

Here is my `.yml` file:
```yml
version: '2'

services:
    haproxy:
        image: haproxy:1.7
        ports:
            # stats
            - "8036:8036"

            # splash
            - "8050:8050"
        links:
            - luminati
            - splash0
            - splash1
            - splash2
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

    splash0:
        image: scrapinghub/splash:3.3.1
        command: --max-timeout 3600 --slots 5 --maxrss 3000 --verbosity 1 --disable-private-mode
        links:
            - luminati
        expose:
            - 8050
        mem_limit: 4200m
        memswap_limit: 5400m
        restart: always

    splash1:
        image: scrapinghub/splash:3.3.1
        command: --max-timeout 3600 --slots 5 --maxrss 3000 --verbosity 1 --disable-private-mode
        links:
            - luminati
        expose:
            - 8050
        mem_limit: 4200m
        memswap_limit: 5400m
        restart: always

    splash2:
        image: scrapinghub/splash:3.3.1
        command: --max-timeout 3600 --slots 5 --maxrss 3000 --verbosity 1 --disable-private-mode
        links:
            - luminati
        expose:
            - 8050
        mem_limit: 4200m
        memswap_limit: 5400m
        restart: always

    luminati:
        image: luminati/luminati-proxy
        command: ["luminati"]
        expose:
          - "22999"
          - "22555"
          - "24000"
        restart: always
```

I'm missing something?

**Comment by nitinmeharia** [comment]
@Urahara Is it solved?

**Comment by Urahara** [comment]
@nitinmeharia I changed to this and now workers the luminati service:

```yaml
    luminati:
        image: luminati/luminati-proxy
        ports:
            # prox manager
            - "22999:22999"
            - "24000:24000"
            - "24001:24001"
            - "24002:24002"
            - "24003:24003"
            - "24004:24004"
            - "24005:24005"
            - "24006:24006"
            - "24007:24007"
            - "24008:24008"
            - "24009:24009"
        expose:
            - 24000
            - 24001
            - 24002
            - 24003
            - 24004
            - 24005
            - 24006
            - 24007
            - 24008
            - 24009
            - 22999
        command: bash -c "cp /my_config.json ./root/.luminati.json && luminati --config ./root/.luminati.json --whitelist_ips 0.0.0.0/0 --www_whitelist_ips 0.0.0.0/0"
        volumes:
            - ./my_config.json:/my_config.json
```
